name: navigation
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.3.0+1

  core:
    path: ../core
  main_page:
    path: ../features/main_page
  settings_page:
    path: ../features/settings_page
  search_page:
    path: ../features/search_page
  home:
    path: ../features/home

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^9.3.1

flutter:
