name: home
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  navigation:
    path: ../../navigation
  core_ui:
    path: ../../core_ui
  core:
    path: ../../core
  domain:
    path: ../../domain
  main_page:
    path: ../../features/main_page
  settings_page:
    path: ../../features/settings_page
  search_page:
    path: ../../features/search_page

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^9.3.1

flutter:

