name: pexels_test_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  settings_page:
    path: features/settings_page
  core:
    path: core
  core_ui:
    path: core_ui
  navigation:
    path: navigation
  domain:
    path: domain

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
