name: main_page
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  core:
    path: ../../core
  domain:
    path: ../../domain
  core_ui:
    path: ../../core_ui

flutter:
