name: core_ui
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  cached_network_image: ^3.4.1
  another_flushbar: ^1.12.30
  
  core:
    path: ../core
  domain:
    path: ../domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

